# Generated by Django 2.2.7 on 2019-11-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0003_remove_cpu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
