# Generated by Django 2.2.7 on 2019-11-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0004_cpu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='price',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
